<Project Sdk="Godot.NET.Sdk/4.5.1">
    <PropertyGroup>
        <!-- 如果你安装了10.0并遇到问题，改下这里 -->
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>true</ImplicitUsings>
        <LangVersion>12.0</LangVersion>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <AssemblyName>Debu999PersonalMod</AssemblyName>

        <!-- 改成你的杀戮尖塔2目录 -->
        <Sts2Dir>F:\SteamLibrary\steamapps\common\Slay the Spire 2</Sts2Dir>
        <Sts2DataDir>$(Sts2Dir)\data_sts2_windows_x86_64</Sts2DataDir>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="0Harmony">
        <HintPath>F:\SteamLibrary\steamapps\common\Slay the Spire 2\data_sts2_windows_x86_64\0Harmony.dll</HintPath>
      </Reference>
        
      <Reference Include="sts2">
        <HintPath>F:\SteamLibrary\steamapps\common\Slay the Spire 2\data_sts2_windows_x86_64\sts2.dll</HintPath>
      </Reference>
        
      <Reference Include="STS2-RitsuLib">
        <HintPath>F:\SteamLibrary\steamapps\common\Slay the Spire 2\mods\STS2-RitsuLib\STS2-RitsuLib.dll</HintPath>
      </Reference>
    </ItemGroup>

    <!-- 自动包含所有 Mod 资源（图片/本地化/配置等） -->
    <ItemGroup>
      <Content Include="Debu999PersonalMod.json" />
      <Content Include="Debu999PersonalMod/**" />
    </ItemGroup>
    <ItemGroup>
      <Folder Include="Debu999PersonalModCode\Powers\" />
    </ItemGroup>

    <!-- 自动复制dll和json -->
    <Target Name="Copy Mod" AfterTargets="PostBuildEvent">
        <Message Text="Copying mod to Slay the Spire 2 mods folder..." Importance="high" />
        <MakeDir Directories="$(Sts2Dir)\mods\" />
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(Sts2Dir)\mods\Debu999PersonalMod\" />
        <Copy SourceFiles="Debu999PersonalMod.json" DestinationFolder="$(Sts2Dir)/mods/Debu999PersonalMod/" />
    </Target>
</Project>
